In [ ]:
### This python File adds number of solves for each problem
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from time import time

In [135]:
prob = pd.read_csv('problems.csv',index_col=['contestId','index']).copy()
prob.dropna(axis=0,inplace=True)
prob['solved'] = 0
#prob.loc[(2035,'H'),'solved'] += 3
prob.head(10)

                                            name  \
contestId index
2035      H             Peak Productivity Forces
          G2            Go Learn! (Hard Version)
          G1            Go Learn! (Easy Version)
          F                      Tree Operations
          E                              Monster
          D      Yet Another Real Number Problem
          C                 Alya and Permutation
          B                  Everyone Loves Tres
          A                              Sliding
2033      G                  Sakurako and Chefir

                                                              tags  rating  \
contestId index
2035      H                            ['constructive algorithms']  3500.0
          G2                          ['divide and conquer', 'dp']  3500.0
          G1                                       ['dp', 'trees']  3300.0
          F      ['binary search', 'brute force', 'dfs and simi...  2500.0
          E      ['binary search', 'brute force', 'constructive...  2300.0
          D      ['binary search', 'data structures', 'divide a...  1800.0
          C        ['bitmasks', 'constructive algorithms', 'math']  1400.0
          B      ['constructive algorithms', 'greedy', 'math', ...   900.0
          A                             ['implementation', 'math']   800.0
2033      G      ['data structures', 'dfs and similar', 'dp', '...  2200.0

                 solved
contestId index
2035      H           0
          G2          0
          G1          0
          F           0
          E           0
          D           0
          C           0
          B           0
          A           0
2033      G           0

In [ ]:
users = pd.read_csv('user2100.csv',index_col='handle')
users.drop(columns=['maxRank','rank','friendOf','lstOnline'],inplace=True)
#user.sort_values(by='regTime',inplace=True)
users.head(5)

,lastName,country,city,rating,firstName,organization,maxRating,regTime
handle,,,,,,,,
tourist,Korotkevich,Belarus,Gomel,4009,Gennady,ITMO University,4009,1265987288
jiangly,Jiang,China,Chongqing,3831,Lingyu,Jiangly Fan Club,3904,1547985852
Radewoosh,Radecki,Poland,Warsaw,3646,Mateusz,University of Warsaw,3759,1385208270
Benq,Qi,United States,Princeton,3620,Benjamin,MIT,3833,1435099979
jqdai0815,Dai,Samoa,Falefa,3620,Jiangqi,National University of Samoa,3681,1306208507

In [ ]:
A=0
B=0
for user in users.index:
    try:
        user_solved = pd.read_csv(f'Submissions/{user}.csv',index_col=['contestId','problem'])
        for row in user_solved.index:
            if row[0] > 3000:
                continue
            try:
                prob.loc[row,'solved'] += 1
            except:
                A += 1 
    except:
        B += 1
        print(user,'Failed!')
        pass

In [138]:
print(A,B)

259614 0

In [139]:
prob[prob.rating >= 2300].drop(columns='tags').sort_values(by='solved',ascending=False).head(30)

                                               name  rating  solved
contestId index
600       E                           Lomsat gelral  2300.0    1769
342       E                          Xenia and Tree  2400.0    1300
438       D                  The Child and Sequence  2300.0    1152
1009      F                        Dominant Indices  2300.0    1090
321       E                       Ciel and Gondolas  2600.0    1078
1916      E                Happy Life in University  2300.0    1078
375       D                        Tree and Queries  2400.0    1075
713       C      Sonya and Problem Wihtout a Legend  2300.0    1071
1870      E                     Another MEX Problem  2300.0    1042
449       D                       Jzzhu and Numbers  2400.0    1007
1919      F1            Wine Factory (Easy Version)  2300.0     979
1083      E             The Fair Nut and Rectangles  2400.0     972
2002      E                             Cosmic Rays  2300.0     943
888       G                                 Xor-MST  2300.0     930
786       B                                  Legacy  2300.0     924
1450      C2          Errich-Tac-Toe (Hard Version)  2300.0     914
13        E                                   Holes  2700.0     914
1942      E                               Farm Game  2300.0     906
868       F        Yet Another Minimization Problem  2500.0     890
1553      F                         Pairwise Modulo  2300.0     882
1428      F                         Fruit Sequences  2400.0     876
1408      F                           Two Different  2300.0     871
558       E                           A Simple Task  2300.0     867
2002      D2             DFS Checker (Hard Version)  2300.0     867
1779      E          Anya's Simultaneous Exhibition  2400.0     864
1305      F               Kuroni and the Punishment  2500.0     863
2006      C                   Eri and Expanded Sets  2300.0     861
1528      C                   Trees of Tranquillity  2300.0     856
1473      E                            Minimum Path  2400.0     854
932       F                     Escape Through Leaf  2700.0     854

In [144]:
prob.to_csv('problemsWithSolved.csv',encoding='utf-8',index=True)